[tool.mypy]
exclude = "build/"


[tool.black]
line-length = 100
target-version = ['py38', 'py39']
include = '\.pyi?$'


[tool.isort]
line_length = 100
force_grid_wrap = 0
include_trailing_comma = true
multi_line_output = 3
use_parentheses = true
